name: Bot deployment notifier
description: Notify the deployment bot
inputs:
  event:
    description: Name of event
    required: true 
  secret:
    description: Webhook secret
    required: false
  url:
    description: Webhook URL
    required: false
outputs:
  result:
    description: Indicates if call was successfull
runs:
  using: 'node12'
  main: 'dist/index.js'
